get http://localhost:8080/api/languages/finnish

###

post http://localhost:8080/api/languages/finnish
content-Type: application/json
{
    "language": "finnish",
    "word": "testi"
}

###
delete http://localhost:8080/api/languages/finnish/4
