get http://localhost:8080/api/languages/finnish

###

post http://localhost:8080/api/languages/english
content-Type: application/json

{"word": "cat"}

###
delete http://localhost:8080/api/languages/finnish/9

###
post http://localhost:8080/api/users/
content-Type: application/json

{"username": "testi", "password": "testi"}

###
get http://localhost:8080/api/users/testi

###

post http://localhost:8080/api/login

content-Type: application/json

{"username": "testi", "password": "testi"}